about.html, index.html, resources.html
made the about and resources links active
=> linked links

about.html, index.html, resources.html
Changed the footers contact email and the url name
=> General email and url

about.html, contact_contribute.html, index.html, resources.html
@jread-usgs @ldecicco-USGS @eread-usgs thoughts?
=> Some text and link additions

resources.html
=> updated resources page

resources.html
=> updated resources page again

gran.html
Added some explanatory text at the top of the page, and made a minor, clarifying addition under GRAN guidelines.
=> amended preliminary and approved distinction text to gran page

gran.html
@ldecicco-USGS review? Can be seen here: http://rawgit.com/jread-usgs/usgs-r-website/master/gran.html
=> modifying disclaimer, adding more install.pkg

gran.html, resources.html
=> Updates from policy feedback

css/style.css, css/style.less, js/application.js, js/templates/review.handlebars, training.html
Stars now generate from the JSON file
=> star generator

css/readme.md, css/style.css, css/style.less, index.html, js/application.js, js/templates/schedule.handlebars, training.html
Switched the reviews to be below the training schedule. 
Made the training schedule a table for later JSON work
Put the twitter widget at the bottom of the index.html
=> table for schedule twitter bottom of page

js/map.js, json/scheduledtrainings.json, rscripts/convert_postworkshop.R, rscripts/convert_scheduledtraining.R
@mwernimont went ahead and made a JSON because it took very little time. There should only be one entry right now because only the one has officially been scheduled. 
FYI for the future: steps to see the site on a localhost url before it's live 
```
In Git Bash:
cd usgs-r-website
git fetch upstream
git merge upstream/master
python -m http.server
```
=> JSON and rscripts for scheduled trainings table

css/style.css, css/style.less, index.html, js/application.js, js/templates/schedule.handlebars, training.html
@jiwalker-usgs want to give my JS a look and see if I need to improve the code?
=> Table pulling JSON for training schedule

json/scheduledtrainings.json, rscripts/convert_postworkshop.R
Always want to have 9 comments (6 good, 3 eh). We currently only have feedback from 8 people
Also, fake json so that @mwernimont can format registration status if it's open to link out to DOI Learn `Open: [DOI LEARN LINK]`
=> filter training feedback differently

css/style.css, css/style.less, js/application.js, js/templates/schedule.handlebars, json/scheduledtrainings.json, training.html
@jiwalker-usgs The if statement looks at the register status and if it says open, a link is generated. Thoughts?
=> register link

js/map.js, rscripts/convert_scheduledtraining.R
google doc of [class roster](https://docs.google.com/a/doi.gov/spreadsheets/d/1TNpL6TfncC7yxrciIegEIWscYpMceL0DQlo9]DGvW6jk/edit?usp=sharing)
=> update info/script based on class roster doc

css/style.css, css/style.less, js/templates/nav.handlebars
@lindsaycarr Training drop down code for actual USGS-R website. The hugo site code to come
=> training dropdown

css/style.css, js/map.js
=> suggested edits for colored markers and legend

index.html
=> remove sbtools in-dev tag

js/templates/nav.handlebars
=> http --> https for nav dropdown

about.html, contact_contribute.html, gran.html, index.html, resources.html, training.html
=> cloudfare keeps failing, use in-repo jquery instead

css/style.css, index.html, js/templates/nav.handlebars, packages.html, training.html
Beginning framework for "Tools Communication":
=> Adding packages tab

js/map.js
Not sure how line 73 needs to be modified since there are no inputs to that layer?
=> added reston, bismarck, and sacramento to map

js/templates/nav.handlebars, rscripts/summarize_course_feedback.Rmd, training.html
I also dealt with a merge conflict in VIM and ended up with some weird spacing and stuff as "changes".
=> remove google form (+ small updates to training summary rmd)
